language: r
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', quiet = TRUE)"
- Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', quiet = TRUE)"
