language: r
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libudunits2-dev # units, sf
      - libgdal-dev     # sf
      - libgeos-dev     # sf
      - libproj-dev     # sf

script:
- travis_wait 60 Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', quiet = TRUE)"
- travis_wait 60 Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', quiet = TRUE)"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  on:
    branch: master
