language: r
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

addons:
  apt:
    packages:
      - libudunits2-dev # units
      - libgdal-dev     # sf
      - libgeos-dev     # sf
      - libproj-dev     # sf

before_install:
- nvm install stable
- npm install netlify-cli -g

script:
- travis_wait 60 Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook', quiet = TRUE)"
- travis_wait 60 Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book', quiet = TRUE)"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: docs
  on:
    branch: master
