<!DOCTYPE html>
<html lang="fr-FR">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>12 Décomposition de l’entropie HCDT | Mesures de la Biodiversité</title>
<meta name="author" content="Eric Marcon">
<meta name="description" content="L’entropie HCDT \(\gamma\) peut être décomposée en somme de l’entropie \(\alpha\) et la moyenne de la divergence entre la distribution de chaque communauté et celle de la méta-communauté....">
<meta name="generator" content="bookdown 0.41 with bs4_book()">
<meta property="og:title" content="12 Décomposition de l’entropie HCDT | Mesures de la Biodiversité">
<meta property="og:type" content="book">
<meta property="og:url" content="https://github.com/EricMarcon/MesuresBioDiv2/chap-DedompHCDT.html">
<meta property="og:image" content="https://github.com/EricMarcon/MesuresBioDiv2/images/logo.png">
<meta property="og:description" content="L’entropie HCDT \(\gamma\) peut être décomposée en somme de l’entropie \(\alpha\) et la moyenne de la divergence entre la distribution de chaque communauté et celle de la méta-communauté....">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="12 Décomposition de l’entropie HCDT | Mesures de la Biodiversité">
<meta name="twitter:description" content="L’entropie HCDT \(\gamma\) peut être décomposée en somme de l’entropie \(\alpha\) et la moyenne de la divergence entre la distribution de chaque communauté et celle de la méta-communauté....">
<meta name="twitter:image" content="https://github.com/EricMarcon/MesuresBioDiv2/images/logo.png">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.8.0/transition.js"></script><script src="libs/bs3compat-0.8.0/tabs.js"></script><script src="libs/bs3compat-0.8.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<!-- Global site tag (gtag.js) - Google Analytics --><script async src="https://www.googletagmanager.com/gtag/js?id=G-C1B3PLBCM6"></script><script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-C1B3PLBCM6');
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="bs4_style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Mesures de la Biodiversité</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Motivation</a></li>
<li><a class="" href="calculs-et-donn%C3%A9es.html">Calculs et données</a></li>
<li><a class="" href="notations.html">Notations</a></li>
<li class="book-part">Notions</li>
<li><a class="" href="chap-Notions.html"><span class="header-section-number">1</span> Notions de Diversité</a></li>
<li><a class="" href="chap-Outils.html"><span class="header-section-number">2</span> Outils</a></li>
<li class="book-part">Diversité neutre d’une communauté</li>
<li><a class="" href="chap-MesuresNeutres.html"><span class="header-section-number">3</span> Mesures neutres de la diversité \(\alpha\) ou \(\gamma\)</a></li>
<li><a class="" href="entropie.html"><span class="header-section-number">4</span> Entropie</a></li>
<li><a class="" href="sec-Equitabilite.html"><span class="header-section-number">5</span> Équitabilité</a></li>
<li class="book-part">Diversité fonctionnelle et phylogénétique</li>
<li><a class="" href="chap-cadrephyfonc.html"><span class="header-section-number">6</span> Cadre</a></li>
<li><a class="" href="mesures-particuli%C3%A8res.html"><span class="header-section-number">7</span> Mesures particulières</a></li>
<li><a class="" href="chap-Phyloentropie.html"><span class="header-section-number">8</span> Entropie phylogénétique</a></li>
<li><a class="" href="chap-LeinsterCobbold.html"><span class="header-section-number">9</span> Diversité de Leinster et Cobbold</a></li>
<li class="book-part">Diversité beta et décomposition</li>
<li><a class="" href="sec-betaCadre.html"><span class="header-section-number">10</span> Cadre</a></li>
<li><a class="" href="chap-BetaPaires.html"><span class="header-section-number">11</span> Diversité de différentiation</a></li>
<li><a class="active" href="chap-DedompHCDT.html"><span class="header-section-number">12</span> Décomposition de l’entropie HCDT</a></li>
<li><a class="" href="d%C3%A9composition-de-la-diversit%C3%A9-phylog%C3%A9n%C3%A9tique-et-fonctionnelle.html"><span class="header-section-number">13</span> Décomposition de la diversité phylogénétique et fonctionnelle</a></li>
<li><a class="" href="tests-de-significativit%C3%A9.html"><span class="header-section-number">14</span> Tests de significativité</a></li>
<li><a class="" href="sec-betaAutres.html"><span class="header-section-number">15</span> Autres approches</a></li>
<li class="book-part">Diversité jointe, diversité structurelle</li>
<li><a class="" href="sec-jointeCadre.html"><span class="header-section-number">16</span> Cadre</a></li>
<li><a class="" href="information-mutuelle.html"><span class="header-section-number">17</span> Information mutuelle</a></li>
<li><a class="" href="chap-DiversiteJointe.html"><span class="header-section-number">18</span> Décomposition de la diversité jointe</a></li>
<li class="book-part">Diversité spatialement explicite</li>
<li><a class="" href="sec-spatialCadre.html"><span class="header-section-number">19</span> Cadre</a></li>
<li><a class="" href="chap-Fisher.html"><span class="header-section-number">20</span> Indice \(\alpha\) de Fisher</a></li>
<li><a class="" href="chap-Accumulation.html"><span class="header-section-number">21</span> Accumulation de la diversité locale</a></li>
<li><a class="" href="diversit%C3%A9-r%C3%A9gionale.html"><span class="header-section-number">22</span> Diversité régionale</a></li>
<li><a class="" href="chap-betasp.html"><span class="header-section-number">23</span> Diversité \(\beta\) spatialement explicite</a></li>
<li class="book-part">Conclusion</li>
<li><a class="" href="sec-conclusionSynthese.html"><span class="header-section-number">24</span> Synthèse</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/EricMarcon/MesuresBioDiv2">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="chap-DedompHCDT" class="section level1" number="12">
<h1>
<span class="header-section-number">12</span> Décomposition de l’entropie HCDT<a class="anchor" aria-label="anchor" href="#chap-DedompHCDT"><i class="fas fa-link"></i></a>
</h1>
<div class="Summary">
<p>L’entropie HCDT <span class="math inline">\(\gamma\)</span> peut être décomposée en somme de l’entropie <span class="math inline">\(\alpha\)</span> et la moyenne de la divergence entre la distribution de chaque communauté et celle de la méta-communauté.
L’entropie <span class="math inline">\(\beta\)</span> est donc interprétable comme le gain d’information apporté par la connaissance de la distribution détaillée des communautés en plus de celle, aggrégée, de la méta-communauté.
L’entropie <span class="math inline">\(\beta\)</span> va de pair avec le nombre effectif de communautés, c’est-à-dire le nombre de communautés de même poids, sans aucune espèce commune, qui fourniraient la même valeur d’entropie <span class="math inline">\(\beta\)</span> que les communautés réelles.
La diversité <span class="math inline">\(\gamma\)</span> se décompose donc en produit du nombre effectif d’espèces de la diversité <span class="math inline">\(\alpha\)</span> et du nombre effectif de communautés.</p>
</div>
<p>Ce chapitre traite de la diversité proportionnelle, qui mesure à quel point les communautés diffèrent de leur assemblage.
Dans la littérature, la diversité <span class="math inline">\(\beta\)</span> est généralement une mesure <em>dérivée</em> <span class="citation">(<a href="references.html#ref-Ellison2010a">Ellison 2010</a>)</span>, c’est-à-dire calculée à partir des diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span>, d’où un abondant débat sur l’indépendance souhaitée mais pas toujours observée entre les valeurs de diversité <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\beta\)</span> <span class="citation">(<a href="references.html#ref-Baselga2010a">Baselga 2010a</a>; <a href="references.html#ref-Jost2010a">Jost 2010a</a>; <a href="references.html#ref-Veech2010a">Veech et Crist 2010</a>)</span>.
Un forum a été consacré à la question dans la revue <em>Ecology</em>, conclu par <span class="citation">Chao, Chiu, et Hsieh (<a href="references.html#ref-Chao2012a">2012</a>)</span>, et une revue a été faite par Tuomisto <span class="citation">(<a href="references.html#ref-Tuomisto2010a">2010a</a>, <a href="references.html#ref-Tuomisto2010b">2010b</a>)</span>.</p>
<p>La décomposition de l’entropie HCDT constitue un cadre cohérent dans lequel la diversité <span class="math inline">\(\beta\)</span> est non seulement une mesure dérivée, mais également une mesure de la divergence entre les distributions des communautés et celle de la méta-communauté.</p>
<div id="décomposition-de-lindice-de-shannon" class="section level2" number="12.1">
<h2>
<span class="header-section-number">12.1</span> Décomposition de l’indice de Shannon<a class="anchor" aria-label="anchor" href="#d%C3%A9composition-de-lindice-de-shannon"><i class="fas fa-link"></i></a>
</h2>

<p></p>
<div class="inline-table"><table class="table table-striped" style="font-size: 9px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:DecShannon">Table 12.1: </span><span id="tab:DecShannon">Table 12.2: </span>Définition explicite de la diversité de Shannon en tant que divergence entre une distribution observée et une distribution attendue. Les indices <span class="math inline">\(H_\alpha\)</span> et <span class="math inline">\(H_\gamma\)</span> sont les compléments au logarithme du nombre d’espèces de cette divergence.
</caption>
<thead><tr>
<th style="text-align:left;">
Indice
</th>
<th style="text-align:left;">
Distribution observée
</th>
<th style="text-align:left;">
Distribution attendue
</th>
<th style="text-align:left;">
Formule
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_\alpha\)</span>
</td>
<td style="text-align:left;">
Fréquence des espèces dans la communauté
</td>
<td style="text-align:left;">
Fréquences égales, hors formule
</td>
<td style="text-align:left;">
<span class="math inline">\(_{i}H_\alpha = \sum_s{p_{s&amp;amp;#124;i}\ln{p_{s&amp;amp;#124;i}}}\)</span>. <span class="math inline">\(H_\alpha = \sum_i{w_i\,_{i}H_\alpha}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_\beta\)</span>
</td>
<td style="text-align:left;">
Fréquence des espèces dans la communauté
</td>
<td style="text-align:left;">
Fréquence totale des espèces
</td>
<td style="text-align:left;">
<span class="math inline">\(_{i}H_\beta = \sum_s{p_{s&amp;amp;#124;i}\ln{p_{s&amp;amp;#124;i}/p_{s}}}\)</span>. <span class="math inline">\(H_\beta = \sum_i{w_i\,_{i}{H}_\beta}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(H_\gamma\)</span>
</td>
<td style="text-align:left;">
Fréquence des espèces dans la méta-communauté
</td>
<td style="text-align:left;">
Fréquences égales, hors formule
</td>
<td style="text-align:left;">
<span class="math inline">\(H_\gamma = \sum_s{p_{s}\ln{p_{s}}}\)</span>
</td>
</tr>
</tbody>
</table></div>
<p></p>
<div id="définition-3" class="section level3" number="12.1.1">
<h3>
<span class="header-section-number">12.1.1</span> Définition<a class="anchor" aria-label="anchor" href="#d%C3%A9finition-3"><i class="fas fa-link"></i></a>
</h3>
<p>La décomposition explicite (tableau <a href="chap-DedompHCDT.html#tab:DecShannon">12.1</a>) est due à <span class="citation">Marcon et al. (<a href="references.html#ref-Marcon2012a">2012</a>)</span> mais avait été établie plus ou moins clairement plusieurs fois dans la littérature, notamment par <span class="citation">Rao et Nayak (<a href="references.html#ref-Rao1985">1985</a>)</span> : la diversité <span class="math inline">\(\beta\)</span> est la divergence de Kullback-Leibler entre la distribution des espèces dans chaque parcelle et la distribution moyenne, appelée divergence de Jensen-Shannon <span class="citation">(<a href="references.html#ref-Lin1991">Lin 1991</a>)</span>.
Les diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span> sont les compléments à <span class="math inline">\(\ln{S}\)</span> des indices de dissimilarité de Theil <a href="entropie.html#eq:Theil">(4.1)</a>, divergences de Kullback-Leibler entre les distributions des espèces et leur équiprobabilité.</p>
<p><span class="citation">Lewontin (<a href="references.html#ref-Lewontin1972">1972</a>)</span>, dans son célèbre article sur la diversité génétique humaine, définit la diversité de Shannon inter-groupe comme la différence entre la diversité totale et la diversité moyenne intra-groupe, mais ne cherche pas à explorer ses propriétés.</p>
<p>La forme de <span class="math inline">\(H_{\beta}\)</span> a été établie par <span class="citation">Ricotta et Avena (<a href="references.html#ref-Ricotta2003a">2003a</a>)</span>, sans la relier à celle de <span class="math inline">\(H_{\alpha}\)</span> et <span class="math inline">\(H_{\gamma}\)</span>.
Enfin, l’idée de la décomposition de la divergence de Kullback-Leibler, mais avec une approche différente, sans rapprochement avec l’indice de Shannon, a été publiée par <span class="citation">Ludovisi et Taticchi (<a href="references.html#ref-Ludovisi2006">2006</a>)</span>.</p>
<p>Les méta-communautés peuvent à leur tour être regroupées à un niveau supérieur, la diversité <span class="math inline">\(\gamma\)</span> du niveau inférieur devenant diversité <span class="math inline">\(\alpha\)</span> pour le niveau supérieur.
La décomposition ou le regroupement peuvent être effectués sur un nombre quelconque de niveaux.</p>
<p>Calcul sous R : La fonction <code>BetaEntropy</code> calcule l’entropie <span class="math inline">\(\beta\)</span> de la méta-communauté (l’argument <span class="math inline">\(q=1\)</span> permet de choisir l’entropie de Shannon).</p>
<p></p>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Pas de correction du biais d'estimation</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/BetaEntropy.html">BetaEntropy</a></span><span class="op">(</span><span class="va">Paracou618.MC</span>, q <span class="op">=</span> <span class="fl">1</span>, Correction <span class="op">=</span> <span class="st">"None"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Neutral beta entropy of order 1 of metaCommunity 
## Paracou618.MC with correction: None 
## 
## Entropy of communities: 
##      P006      P018 
## 0.3499358 0.5771645 
## Average entropy of the communities: 
## [1] 0.4471751</code></pre>
<p></p>
</div>
<div id="sec-BiaisShannonBeta" class="section level3" number="12.1.2">
<h3>
<span class="header-section-number">12.1.2</span> Biais d’estimation<a class="anchor" aria-label="anchor" href="#sec-BiaisShannonBeta"><i class="fas fa-link"></i></a>
</h3>
<p>L’estimateur du taux de couverture de la communauté <span class="math inline">\(i\)</span> est noté <span class="math inline">\(\hat{C}_i\)</span>, le taux de couverture total <span class="math inline">\(\hat{C}\)</span>.
L’estimateur corrigé de <span class="math inline">\(_iH_{\beta}\)</span> est</p>
<p><span class="math display" id="eq:EstHbetai">\[\begin{equation}
  \tag{12.1}
  _{i}\tilde{H}_{\beta} = \sum^{s_{\ne 0}}_{i=1}{\frac{{\hat{C}}_i{\hat{p}}_{s|i} \ln\frac{{\hat{C}}_i{\hat{p}}_{s|i}}{\hat{C}{\hat{p}}_s}}{1-{\left(1-{\hat{C}}_i{\hat{p}}_{s|i}\right)}^n}}.
\end{equation}\]</span></p>
<p>Calcul sous R : <code>BetaEntropy</code> applique cette correction :</p>
<p></p>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/BetaEntropy.html">BetaEntropy</a></span><span class="op">(</span><span class="va">Paracou618.MC</span>, q <span class="op">=</span> <span class="fl">1</span>, Correction <span class="op">=</span> <span class="st">"ChaoShen"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Neutral beta entropy of order 1 of metaCommunity 
## Paracou618.MC with correction: ChaoShen 
## 
## Entropy of communities: 
##      P006      P018 
## 0.2949188 0.4514132 
## Average entropy of the communities: 
## [1] 0.3618884</code></pre>
<p></p>
<p><span class="citation">Chao, Wang, et Jost (<a href="references.html#ref-Chao2013">2013</a>)</span> utilisent une approche différente pour corriger le biais d’estimation : l’information mutuelle.
Les données sont organisées comme dans le tableau <a href="sec-betaCadre.html#tab:Notations">10.1</a>, mais les probabilités qu’un individu appartienne à la communauté <span class="math inline">\(i\)</span> et à l’espèce <span class="math inline">\(s\)</span> sont calculées pour que leur somme soit égale à 1 sur l’ensemble du tableau : <span class="math inline">\(\sum_s{\sum_i{p_{s,i}}}=1\)</span> (au lieu de <span class="math inline">\(\sum_i{p_{s|i}}=1\)</span>).</p>
<p>L’information mutuelle est la divergence de Kullback-Leibler entre la distribution de <span class="math inline">\(\{p_{s,i}\}\)</span> et celle du produit des distributions marginales <span class="math inline">\(\{p_s\}\)</span> et <span class="math inline">\(\{p_i\}\)</span>.
Si les distributions marginales sont indépendantes, la probabilité <span class="math inline">\(p_{s,i}\)</span> qu’un individu appartienne à l’espèce <span class="math inline">\(s\)</span> et se trouve dans la communauté <span class="math inline">\(i\)</span> est donnée par le produit des probabilités marginales <span class="math inline">\(p_s\)</span> et <span class="math inline">\(p_i\)</span>, et l’information mutuelle est nulle.</p>
<p>L’information mutuelle se calcule comme la différence entre l’entropie de Shannon calculée sur l’ensemble du tableau <span class="math inline">\(H(\{p_{s,i}\})\)</span> et les entropies marginales <span class="math inline">\(H(\{p_s\})\)</span> et <span class="math inline">\(H(\{p_i\})\)</span>.
<span class="math inline">\(H(\{p_s\})\)</span> est l’entropie <span class="math inline">\(\gamma\)</span> de la méta-communauté.
Si on choisit de pondérer les communautés par leurs effectifs (<span class="math inline">\(w_i=p_i\)</span>), alors <span class="math inline">\(H(\{p_{s,i}\})-H(\{p_i\})\)</span> est l’entropie <span class="math inline">\(\alpha\)</span> de la méta-communauté, c’est-à-dire la moyenne pondérée des entropies <span class="math inline">\(\alpha\)</span> des communautés.
Dans ce cas, l’entropie <span class="math inline">\(\beta\)</span> est égale à l’opposée de l’information mutuelle.
Comme chaque terme du calcul est une entropie <span class="math inline">\(\alpha\)</span>, il peut être corrigé selon l’équation <a href="chap-MesuresNeutres.html#eq:Chao2013">(3.41)</a> pour obtenir un estimateur moins biaisé de <span class="math inline">\(H_{\beta}\)</span>.</p>
<p>Calcul sous R :</p>
<p></p>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/Shannon.html">Shannon</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Ns</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/Shannon.html">Shannon</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Nsi</span><span class="op">)</span><span class="op">)</span> <span class="op">-</span></span>
<span>    <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/Shannon.html">Shannon</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Nsi</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   UnveilJ 
## 0.3439827</code></pre>
<p></p>
<p>Cet estimateur est le moins biaisé à ce jour, mais n’est applicable qu’à l’entropie de Shannon, sous la condition que la pondération des communautés soit donnée par les effectifs.</p>
<p><span class="citation">Z. Zhang et Grabchak (<a href="references.html#ref-Zhang2014a">2014</a>)</span> proposent un estimateur de la divergence de Kullback-Leibler avec un biais réduit selon la même méthode que pour l’estimation de l’entropie HCDT ou de l’entropie de Shannon :</p>
<p><span class="math display" id="eq:Zhang2014a">\[\begin{align}
  \tag{12.2}
  _{i}\tilde{H}_{\beta}
  &amp;= \sum^{s_{\ne 0}}_{s=1}{\frac{n_{s,i}}{n} }\\
    &amp;\left\{ \sum^{n-n_s}_{v=1}{\frac{1}{v} \prod^v_{j=1}{ \left( 1-\frac{n_s}{n-j+1} \right) }}
     -  \sum^{n_i-n_{s,i}}_{v=1}{\frac{1}{v} \prod^v_{j=1}{\left( 1-\frac{n_{s,i}-1}{n_i-j} \right) }} \right\}.
\end{align}\]</span></p>
<p>Cette correction est incluse dans la fonction <code>ShannonBeta</code> de <em>entropart</em> :</p>
<p></p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Divergence de Kullback-Leibler entre chaque communauté de</span></span>
<span><span class="co"># Paracou618.MC et la métacommunauté</span></span>
<span><span class="op">(</span><span class="va">Beta</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Nsi</span>, <span class="fl">2</span>, <span class="va">ShannonBeta</span>, Nexp <span class="op">=</span> <span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Ns</span>,</span>
<span>    Correction <span class="op">=</span> <span class="st">"ZhangGrabchak"</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      P006      P018 
## 0.1442318 0.2994995</code></pre>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Entropie beta</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Wi</span> <span class="op">*</span> <span class="va">Beta</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] 0.2106764</code></pre>
<p></p>
<p>La correction de Zhang et Grabchak réduit beaucoup plus fortement l’estimation que celle de Chao et Shen.
Le meilleur estimateur peut être évalué à partir de la différence entre les entropies <span class="math inline">\(\gamma\)</span> et <span class="math inline">\(\alpha\)</span>, corrigées par le meilleur estimateur disponible (celui de Chao, Wang et Jost, voir section <a href="chap-MesuresNeutres.html#sec-BiaisShannon">3.3.2</a>) :</p>
<p></p>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Entropie alpha de chaque communauté de Paracou618.MC</span></span>
<span><span class="op">(</span><span class="va">Alpha</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Nsi</span>, <span class="fl">2</span>, <span class="va">Shannon</span>, CheckArguments <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     P006     P018 
## 4.427559 4.772981</code></pre>
<div class="sourceCode" id="cb282"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Entropie beta estimée par différence</span></span>
<span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/Shannon.html">bcShannon</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Ns</span><span class="op">)</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="va">Paracou618.MC</span><span class="op">$</span><span class="va">Wi</span> <span class="op">*</span> <span class="va">Alpha</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   UnveilJ 
## 0.3526572</code></pre>
<p></p>
<p>L’estimateur de Chao et Shen est apparemment le meilleur, la correction de celui de Zhang et Grabchak est trop forte.</p>
</div>
</div>
<div id="décomposition-de-lentropie-généralisée" class="section level2" number="12.2">
<h2>
<span class="header-section-number">12.2</span> Décomposition de l’entropie généralisée<a class="anchor" aria-label="anchor" href="#d%C3%A9composition-de-lentropie-g%C3%A9n%C3%A9ralis%C3%A9e"><i class="fas fa-link"></i></a>
</h2>
<p>La décomposition additive de l’entropie selon <span class="citation">Lande (<a href="references.html#ref-Lande1996">1996</a>)</span> doit être la suivante :</p>
<p><span class="math display" id="eq:DecompHq">\[\begin{equation}
  \tag{12.3}
  ^{q}\!H_{\gamma} = {^{q}\!H_{\alpha}} + {^{q}\!H_{\beta}}.
\end{equation}\]</span></p>
<p><span class="citation">Bourguignon (<a href="references.html#ref-Bourguignon1979">1979</a>)</span> comme <span class="citation">Lande (<a href="references.html#ref-Lande1996">1996</a>)</span> définissent une mesure d’inégalité décomposable comme respectant les propriétés suivantes :</p>
<ul>
<li>La population totale étant partitionnée, chaque partition recevant un poids <span class="math inline">\(w_i\)</span>, la composante intra-groupe de la mesure <span class="math inline">\(H_{\alpha}\)</span> est égale à la somme pondérée des mesures dans chaque-groupe <span class="math inline">\(H_{\alpha}=\sum_i{w_i {_{i}\!H_{\alpha}}}\)</span><span style="white-space:nowrap"> ;</span>
</li>
<li>La composante intergroupe <span class="math inline">\(H_{\beta}\)</span> est la mesure d’inégalité entre les <span style="white-space:nowrap">groupes ;</span>
</li>
<li>La mesure totale <span class="math inline">\(H_{\gamma}\)</span> est la somme des mesures intra et intergroupes.</li>
</ul>
<p>En passant par les nombres de Hill, <span class="citation">Jost (<a href="references.html#ref-Jost2007">2007</a>)</span> montre que l’indice de Shannon est le seul pouvant être décomposé de cette façon.</p>
<p>La démonstration de Jost repose sur le postulat que la transformation de l’entropie en nombre de Hill, définie pour la diversité <span class="math inline">\(\alpha\)</span>, doit avoir la même forme pour la diversité <span class="math inline">\(\beta\)</span>.
La remise en cause de ce postulat <span class="citation">(<a href="references.html#ref-Marcon2014a">Marcon et al. 2014</a>)</span> permet de décomposer la diversité d’ordre quelconque quel que soit le poids des communautés.</p>
<p>La décomposition de l’entropie est faite en écrivant le logarithme d’ordre <span class="math inline">\(q\)</span> de la décomposition de la diversité, équation <a href="sec-betaCadre.html#eq:DecompDq">(10.1)</a> :</p>
<p><span class="math display" id="eq:DecompJost">\[\begin{equation}
  \tag{12.4}
  ^{q}\!H_{\gamma} = {^{q}\!H_{\alpha}}+\ln_q{^{q}\!D_{\beta}}-\left(q-1\right){^{q}\!H_{\alpha}}\ln_q{^{q}\!D_{\beta}}.
\end{equation}\]</span></p>
<p>Ceci est la décomposition de <span class="citation">Jost (<a href="references.html#ref-Jost2007">2007</a>)</span>.
Jost désigne sous le nom de “composante <span class="math inline">\(\beta\)</span> de l’entropie” le logarithme d’ordre <span class="math inline">\(q\)</span> de la diversité, qu’il note <span class="math inline">\(H_B\)</span>.
La décomposition n’est pas additive, mais <span class="math inline">\(H_B\)</span> est indépendant de l’entropie <span class="math inline">\(\alpha\)</span>.</p>
<p>Les deux derniers termes peuvent être regroupés et réarrangés pour obtenir <span class="math inline">\(^{q}\!H_{\beta}\)</span> conformément à la décomposition additive de l’équation <a href="chap-DedompHCDT.html#eq:DecompHq">(12.3)</a> :</p>
<p><span class="math display" id="eq:ContributionBeta">\[\begin{equation}
  \tag{12.5}
  ^{q}\!H_{\beta} = \sum_i{w_i\sum_s{p^q_{s|i}\ln_q\frac{p_{s|i}}{p_s}}}.
\end{equation}\]</span></p>
<p>L’entropie <span class="math inline">\(\beta\)</span> est la somme pondérée par <span class="math inline">\(w_i\)</span> (et pas autrement) des contributions de chaque communauté :</p>
<p><span class="math display" id="eq:PoidsHbetai">\[\begin{equation}
  \tag{12.6}
  ^{q}_{i}\!H_{\beta}=\sum_s{p^q_{s|i}\ln_q\frac{p_{s|i}}{p_s}}.
\end{equation}\]</span></p>
<p><span class="math inline">\(^{q}_{i}\!H_{\beta}\)</span> est une divergence de Kullback-Leibler généralisée <span class="citation">(<a href="references.html#ref-Borland1998">Borland, Plastino, et Tsallis 1998</a>; <a href="references.html#ref-Tsallis1998">Tsallis, Mendes, et Plastino 1998</a>)</span>.
<span class="math inline">\(^{q}\!H_{\beta}\)</span> en est la moyenne sur l’ensemble des communautés, c’est donc une généralisation de la divergence de Jensen-Shannon <span class="citation">(<a href="references.html#ref-Marcon2014a">Marcon et al. 2014</a>)</span>.
<span class="math inline">\(^{q}\!H_{\gamma}\)</span> peut s’écrire sous la forme <span class="math inline">\(^{q}\!H_{\gamma} = -\sum_s{p^q_s}\ln_q{p_s}\)</span> : la formalisation de la décomposition est une généralisation de la décomposition de l’entropie de Shannon, résumée dans le tableau <a href="chap-DedompHCDT.html#tab:Decomposition">12.3</a>.</p>
<p>Il est intéressant d’écrire <span class="math inline">\(^{q}_{i}\!H_{\beta}\)</span> et <span class="math inline">\(^{q}\!H_{\gamma}\)</span> sous la forme d’entropies, pour faire apparaître leur fonction d’information.
Pour <span class="math inline">\(q\)</span> différent de 1, l’entropie <span class="math inline">\(\gamma\)</span> est</p>
<p><span class="math display" id="eq:Hqgamma">\[\begin{equation}
  \tag{12.7}
  ^{q}\!H_{\gamma}
  = \sum_s{p_s\frac{1-p^{q-1}_s}{q-1}}
  = \sum_s{p_s\ln_q\frac{1}{p_s}}.
\end{equation}\]</span></p>
<p>Sa fonction d’information a été tracée figure <a href="entropie.html#fig:IFig">4.1</a>.</p>
<p>L’entropie <span class="math inline">\(\beta\)</span> est</p>
<p><span class="math display" id="eq:Hqbeta">\[\begin{equation}
  \tag{12.8}
  ^{q}_{i}\!H_{\beta}
  = \sum_s{p_{s|i}\frac{p^{q-1}_{s|i}-p^{q-1}_s}{q-1}}
  = \sum_s{p_{s|i}\left(\ln_q\frac{1}{p_s}-\ln_q\frac{1}{p_{s|i}}\right)}.
\end{equation}\]</span></p>
<p>La forme de l’entropie <span class="math inline">\(\beta\)</span> évoque la divergence de puissance <span class="citation">(<a href="references.html#ref-Cressie1984">N. Cressie et Read 1984</a>)</span> qui est une statistique qui mesure la divergence entre deux distributions dont les propriétés asymptotiques sont connues.
La divergence de puissance peut être écrite sous la forme <span class="math inline">\(I_q= \frac{-2}{q} \sum_s{p_{s|i} \ln_q\frac{p_{s}}{p_{s|i}}}\)</span>.
Elle est égale à (deux fois) la divergence de Kullback-Leibler pour <span class="math inline">\(q=1\)</span>, mais diffère de l’entropie <span class="math inline">\(\beta\)</span> pour les autres valeurs de <span class="math inline">\(q\)</span>.
La divergence non-logarithmique de Jensen-Shannon <span class="citation">(<a href="references.html#ref-Lamberti2003">Lamberti et Majtey 2003</a>)</span> est identique à une normalisation près : <span class="math inline">\(K_q= -\sum_s{p_{s|i} \ln_q\frac{p_{s}}{p_{s|i}}}\)</span>.
Elle mesure l’écart entre la diversité <span class="math inline">\(\alpha\)</span> et la valeur de <span class="math inline">\(\sum_s{w_i p^q_{s|i} \ln_q{p_s}^q}\)</span>, qui n’est pas la diversité <span class="math inline">\(\gamma\)</span> <span class="citation">(<a href="references.html#ref-Marcon2014a">Marcon et al. 2014</a>)</span>.</p>
<p>Calcul sous R : La fonction <code>DivPart</code> calcule entropie et diversité en même temps :</p>
<p></p>
<div class="sourceCode" id="cb284"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/DivPart.html">DivPart</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">1</span>, <span class="va">Paracou618.MC</span>, Biased <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span></code></pre></div>
<pre><code>## $MetaCommunity
## [1] "Paracou618.MC"
## 
## $Order
## [1] 1
## 
## $Biased
## [1] FALSE
## 
## $Correction
## [1] "UnveilJ"
## 
## $Normalized
## [1] TRUE
## 
## $TotalAlphaDiversity
## [1] 97.06467
## 
## $TotalBetaDiversity
##  UnveilJ 
## 1.422843 
## 
## $GammaDiversity
##  UnveilJ 
## 138.1078 
## 
## $CommunityAlphaDiversities
##     P006     P018 
##  83.7268 118.2713 
## 
## $TotalAlphaEntropy
## [1] 4.575378
## 
## $TotalBetaEntropy
##   UnveilJ 
## 0.3526572 
## 
## $GammaEntropy
##  UnveilJ 
## 4.928035 
## 
## $CommunityAlphaEntropies
##     P006     P018 
## 4.427559 4.772981 
## 
## $CommunityBetaEntropies
## [1] NA
## 
## $Method
## [1] "HCDT"
## 
## attr(,"class")
## [1] "DivPart"</code></pre>
<p></p>
</div>
<div id="décomposition-du-nombre-despèces" class="section level2" number="12.3">
<h2>
<span class="header-section-number">12.3</span> Décomposition du nombre d’espèces<a class="anchor" aria-label="anchor" href="#d%C3%A9composition-du-nombre-desp%C3%A8ces"><i class="fas fa-link"></i></a>
</h2>
<p>Les résultats généraux se simplifient pour <span class="math inline">\(q=0\)</span>.
L’entropie <span class="math inline">\(\gamma\)</span> est le nombre d’espèces de la méta-communauté moins un (<span class="math inline">\(^{0}\!H_{\gamma}=S-1\)</span>), l’entropie <span class="math inline">\(\alpha\)</span> est la moyenne pondérée du nombre d’espèces des communautés moins un (<span class="math inline">\(^{0}\!H_{\alpha}=\bar{S}-1\)</span>), l’entropie <span class="math inline">\(\beta\)</span> est la différence : <span class="math inline">\(^{0}\!H_{\beta}=S-\bar{S}\)</span>.</p>
<p>En termes de diversité,</p>
<p><span class="math display" id="eq:D0beta">\[\begin{equation}
  \tag{12.9}
  ^{0}\!D_{\beta}=\frac{S}{\bar{S}}.
\end{equation}\]</span></p>
<p><span class="math inline">\(^{0}\!D_{\beta}\)</span> peut être supérieur au nombre de communautés <span class="citation">(<a href="references.html#ref-Chao2012a">Chao, Chiu, et Hsieh 2012</a>)</span> si les poids sont très inégaux, ce qui complique son interprétation.
La pondération de Jost donne pour le nombre d’espèces le même poids à toutes les communautés et garantit <span class="math inline">\(^{0}\!D_{\beta}\le I\)</span>, ce qui constitue pour Chao et al. un argument en faveur de son utilisation.
Un contre-argumentaire est fourni par <span class="citation">Marcon et al. (<a href="references.html#ref-Marcon2014a">2014</a>)</span>.
Quel que soit la distribution des poids des communautés, il est toujours possible de ramener les données à un ensemble de communautés de poids identiques, dont certaines sont répétées.
La communauté dont le poids <span class="math inline">\(w_{min}\)</span> est le plus faible est représentée une seule fois, les autres <span class="math inline">\({w_i}/{w_{min}}\)</span> fois.
L’indépendance entre les diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\beta\)</span> est donc bien vérifiée.
Le diversité <span class="math inline">\(\beta\)</span> maximale théorique est <span class="math inline">\({1}/{w_{min}}\)</span> (et non <span class="math inline">\(I\)</span>).
Elle n’est pas atteinte parce que plusieurs communautés sont identiques.</p>
<p>La définition de la diversité <span class="math inline">\(\beta\)</span> par <span class="citation">Whittaker (<a href="references.html#ref-Whittaker1960">1960</a>)</span> s’appliquait aux données de présence-absence.
La diversité <span class="math inline">\(\beta\)</span> était le rapport entre le nombre d’espèces total de l’assemblage des communautés (diversité <span class="math inline">\(\gamma\)</span>) et le nombre moyen d’espèces dans chaque communauté (diversité <span class="math inline">\(\alpha\)</span>).
C’est précisément la définition de <span class="math inline">\(^{0}\!D_{\beta}\)</span> <a href="chap-DedompHCDT.html#eq:D0beta">(12.9)</a>.</p>
</div>
<div id="décomposition-de-lindice-de-gini-simpson" class="section level2" number="12.4">
<h2>
<span class="header-section-number">12.4</span> Décomposition de l’indice de Gini-Simpson<a class="anchor" aria-label="anchor" href="#d%C3%A9composition-de-lindice-de-gini-simpson"><i class="fas fa-link"></i></a>
</h2>
<p>L’entropie de Simpson peut aussi être décomposée comme une variance.
La probabilité qu’un individu appartienne à l’espèce <span class="math inline">\(s\)</span> est <span class="math inline">\(p_s\)</span>.
Elle suit une loi de Bernoulli, dont la variance est <span class="math inline">\(p_s\left(1-p_s\right)\)</span>.
Cette variance peut être décomposée entre les communautés, où la probabilité est <span class="math inline">\(p_{s|i}\)</span>.
La décomposition entre variance intra et inter-communautés est</p>
<p><span class="math display" id="eq:DecSimpsons">\[\begin{equation}
  \tag{12.10}
  p_s\left(1-p_s\right)=\sum_i{w_i\left[p_{s|i}\left(1-p_{s|i}\right)+{\left(p_{s|i}-p_s\right)}^2\right]}.
\end{equation}\]</span></p>
<p>Cette égalité peut être sommée sur toutes les espèces pour donner</p>
<p><span class="math display" id="eq:SimpsonNei">\[\begin{equation}
  \tag{12.11}
  E_{\gamma}=\sum_i{w_i E_{\alpha,i}}+\sum_i{w_i\sum_s{{\left(p_{s|i}-p_s\right)}^2}}=E_{\alpha}+E_{\beta}.
\end{equation}\]</span></p>
<p>L’entropie <span class="math inline">\(\gamma\)</span> de Simpson peut être décomposée en sa diversité <span class="math inline">\(\alpha\)</span>, somme pondérée des entropies <span class="math inline">\(\alpha\)</span> des communautés, et son entropie <span class="math inline">\(\beta\)</span>, égale à la somme pondérée des distances <span class="math inline">\(l^2\)</span> entre la distribution des fréquences dans chaque communauté et celle de l’ensemble de la communauté.</p>
<p>En génétique, l’égalité s’écrit<span class="citation">(<a href="references.html#ref-Nei1973">Nei 1973</a>)</span> <span class="math inline">\(H_t=H_s+D_{s,t}\)</span>.
<span class="math inline">\(H_t\)</span> est l’hétérozygotie totale, décomposée en <span class="math inline">\(H_s\)</span>, l’hétérozygotie moyenne des populations et <span class="math inline">\(D_{s,t}\)</span> la différenciation absolue entre populations.
<span class="math inline">\(G_{s,t}={D_{s,t}}/{H_t}\)</span> est la différenciation relative.</p>
<p>L’entropie <span class="math inline">\(E_{\beta}\)</span> calculée de cette manière est égale à <span class="math inline">\(^{2}\!H_{\beta}\)</span> calculée à l’équation <a href="chap-DedompHCDT.html#eq:Hqbeta">(12.8)</a> pour le cas général, mais la contribution de chaque communauté est différente : la décomposition de la variance est une façon alternative de décomposer l’entropie, valable uniquement pour l’entropie de Simpson.</p>
<p>Cette décomposition est remise en cause par Jost <span class="citation">(<a href="references.html#ref-Jost2007">Jost 2007</a>, <a href="references.html#ref-Jost2008">2008</a>)</span> qui a généré le débat <span class="citation">(<a href="references.html#ref-Heller2009">Heller et Siegismund 2009</a>; <a href="references.html#ref-Ryman2009">Ryman et Leimar 2009</a>; <a href="references.html#ref-Jost2009a">Jost 2009a</a>; <a href="references.html#ref-Whitlock2011">Whitlock 2011</a>)</span>.
<span class="math inline">\(E_{\gamma}\)</span> étant inférieure ou égale à 1, <span class="math inline">\(E_{\beta}\)</span> n’est pas indépendante de <span class="math inline">\(E_{\alpha}\)</span> : seule la décomposition multiplicative permet l’indépendance, et Jost propose d’utiliser une transformation de <span class="math inline">\(^{2}\!D_{\beta}\)</span> comme mesure de différenciation (voir section <a href="chap-DedompHCDT.html#sec-Chevauchement">12.7.2</a>). <span class="citation">Gregorius (<a href="references.html#ref-Gregorius2014">2014</a>)</span> montre que ce problème n’est pas limité à l’entropie de Simpson mais s’applique à toutes les entropies HCDT d’ordre supérieur à 1.</p>
<p>Jost postule que la diversité <span class="math inline">\(\beta\)</span> de Simpson a la même relation à <span class="math inline">\(E_{\beta}\)</span> que les diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span>,</p>
<p><span class="math display" id="eq:Dqgamma">\[\begin{equation}
  \tag{12.12}
  ^{q}\!D_{\gamma} = {^{q}\!D_{\alpha}}{^{q}\!D_{\beta}} \Leftrightarrow \frac{1}{1-E_{\gamma}}=\frac{1}{1-E_{\alpha}}\frac{1}{1-E_{\beta}},
\end{equation}\]</span></p>
<p>d’où une décomposition additive différente, qui correspond à sa décomposition générale <a href="chap-DedompHCDT.html#eq:DecompJost">(12.4)</a> :</p>
<p><span class="math display" id="eq:Egamma">\[\begin{equation}
  \tag{12.13}
  E_{\gamma}=E_{\alpha}+E_{\beta}-{E_{\alpha}}{E_{\beta}}.
\end{equation}\]</span></p>
<p>Il n’y a en réalité aucune raison pour que le nombre équivalent de la diversité <span class="math inline">\(\beta\)</span> ait la même forme que celle de la diversité <span class="math inline">\(\alpha\)</span> : les deux diversités sont par nature très différentes, et Hill ne traitait pas la diversité <span class="math inline">\(\beta\)</span>.
La diversité de Shannon est exceptionnelle parce que, pour des raisons différentes, son nombre de Hill est l’exponentielle de l’entropie, et l’exponentielle de la décomposition additive <a href="chap-DedompHCDT.html#eq:DecompHq">(12.3)</a> est la décomposition multiplicative <a href="sec-betaCadre.html#eq:DecompDq">(10.1)</a>.</p>

<p></p>
<div class="inline-table"><table class="table table-striped" style="font-size: 6px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:Decomposition">Table 12.3: </span><span id="tab:Decomposition">Table 12.4: </span>Entropie, diversité et décomposition. L’entropie <span class="math inline">\(\alpha\)</span> de chaque communauté se calcule comme l’entropie <span class="math inline">\(\gamma\)</span>
</caption>
<thead><tr>
<th style="text-align:left;">
Mesure de diversité
</th>
<th style="text-align:left;">
Entropie généralisée
</th>
<th style="text-align:left;">
Shannon
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Entropie <span class="math inline">\(\gamma\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{q}\!H_{\gamma}=-\sum_s{p^q_s}\ln_q{p_s}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{1}\!H_{\gamma}=-\sum_s{p_s}\ln{p_s}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Entropie <span class="math inline">\(\beta\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{q}\!H_{\beta}=\sum_i{w_i\sum_s{p_{s&amp;amp;#124;i}\left(\ln_q\frac{1}{p_s}-\ln_q\frac{1}{p_{s&amp;amp;#124;i}}\right)}}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{1}\!H_{\beta}=\sum_i{w_i\sum_s{p_{s&amp;amp;#124;i}\ln\frac{p_{s&amp;amp;#124;i}}{p_s}}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Diversité <span class="math inline">\(\gamma\)</span> (nombre de Hill)
</td>
<td style="text-align:left;">
<span class="math inline">\(^{q}\!D_{\gamma}=e^{^q\!H_{\gamma}}_q\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{1}\!D_{\gamma}=e^{^1\!H_\gamma}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Diversité <span class="math inline">\(\beta\)</span> (nombre équivalent
</td>
<td style="text-align:left;">
<span class="math inline">\(^{q}\!D_{\beta}=e^{\frac{^{q}\!H_{\beta}}{1-(q-1)^{q}\!H_{\alpha}}}_q\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(^{1}\!D_{\beta}=e^{^{1}\!H_{\beta}}\)</span>
</td>
</tr>
</tbody>
</table></div>
<p></p>
<p>Le nombre équivalent de communautés a une forme légèrement différente d’un nombre de Hill (tableau <a href="chap-DedompHCDT.html#tab:Decomposition">12.3</a>).</p>
</div>
<div id="sec-RaoDisc" class="section level2" number="12.5">
<h2>
<span class="header-section-number">12.5</span> Décomposition de l’indice de Rao<a class="anchor" aria-label="anchor" href="#sec-RaoDisc"><i class="fas fa-link"></i></a>
</h2>
<p>Les notations sont celles de la présentation de l’indice de Rao, section <a href="mesures-particuli%C3%A8res.html#sec-Rao">7.6</a>.</p>
<p>La diversité de la méta-communauté, peut être décomposée en une somme (pondérée) de diversités intra et une diversité inter <span class="citation">(<a href="references.html#ref-Pavoine2004">Pavoine, Dufour, et Chessel 2004</a>)</span> en définissant une dissimilarité entre les communautés <span class="math inline">\(i\)</span> et <span class="math inline">\(j\)</span> :</p>
<p><span class="math display" id="eq:DHdelta">\[\begin{equation}
  \tag{12.14}
  D_{H_{\Delta }}\left(\mathbf{p}_i,\mathbf{p}_j\right)
  = 2 H_{\Delta}\left(\frac{\mathbf{p}_{i}+\mathbf{p}_j}{2}\right)
  -H_{\Delta}\left(\mathbf{p}_i\right)-H_{\Delta}\left(\mathbf{p}_j\right).
\end{equation}\]</span></p>
<p>Elle est définie par Rao comme la différence entre l’entropie quadratique du mélange des deux communautés et celles des deux communautés prises individuellement.
Elle peut être utilisée pour calculer un indice de diversité entre communautés, de la même façon qu’on calcule la diversité entre espèces d’une communauté :</p>
<p><span class="math display" id="eq:Raobeta">\[\begin{equation}
  \tag{12.15}
  H_{\Delta }\left(\mathbf{p}\right) = \sum_i{w_i H_{\Delta }\left({\mathbf{p}}_i\right)}+\sum_i{\sum_j{w_i w_j D_{H_{\Delta }}\left({\mathbf{p}}_i,{\mathbf{p}}_j\right)}}.
\end{equation}\]</span></p>
<p>Le deuxième terme de la somme est la diversité inter-communautés.
C’est un indice de Rao : les poids des communautés sont équivalents aux tableaux de fréquences et les dissimilarités entre communautés sont équivalentes aux dissimilarités entre espèces de l’équation <a href="mesures-particuli%C3%A8res.html#eq:Rao">(7.20)</a>.
La divergence entre communautés est construite à partir des entropies de chacune : l’entropie <span class="math inline">\(\beta\)</span> est définie comme la différence entre les entropies <span class="math inline">\(\gamma\)</span> et <span class="math inline">\(\alpha\)</span>.</p>
<p>L’exemple suivant utilise les communautés du fichier <code>rao.effectifs.csv</code> :</p>
<p></p>
<div class="sourceCode" id="cb286"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Vecteur contenant 8 espèces...</span></span>
<span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv2</a></span><span class="op">(</span><span class="st">"data/rao.effectifs.csv"</span>, row.names <span class="op">=</span> <span class="fl">1</span>, header <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">-&gt;</span></span>
<span>    <span class="va">effectifs</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     P1 P2 P3 P4
## Ess 97 36 34 61
## Me  62 24 49  4
## S1   4  6  6 75
## Sr  71 78 99 36
## Vm  76 29 34  2
## Bg  58 49 47 19
## Ef   9 34 91 35
## Dg  98 14 95 14</code></pre>
<div class="sourceCode" id="cb288"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Lecture des données : traits pour 34 espèces</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv2</a></span><span class="op">(</span><span class="st">"data/rao.traits.csv"</span>, row.names <span class="op">=</span> <span class="fl">1</span>, header <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="op">-&gt;</span></span>
<span>    <span class="va">traits</span></span>
<span><span class="co"># ACP sur les traits foliaires</span></span>
<span><span class="va">pcaf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ade4/man/dudi.pca.html">dudi.pca</a></span><span class="op">(</span><span class="va">traits</span>, scale <span class="op">=</span> <span class="cn">T</span>, scannf <span class="op">=</span> <span class="cn">FALSE</span>, nf <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span>
<span><span class="co"># CAH Ward des traits foliaires</span></span>
<span><span class="va">hf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/hclust.html">hclust</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span><span class="op">(</span><span class="va">pcaf</span><span class="op">$</span><span class="va">tab</span><span class="op">)</span>, <span class="st">"ward.D"</span><span class="op">)</span></span>
<span><span class="co"># Transformation de l'arbre du format hclust au format</span></span>
<span><span class="co"># phylog</span></span>
<span><span class="va">phyf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ade4/man/newick2phylog.html">hclust2phylog</a></span><span class="op">(</span><span class="va">hf</span><span class="op">)</span></span></code></pre></div>
<p></p>
<p>Il contient 4 communautés.</p>
<p>Pour obtenir tous les éléments de l’équation <a href="chap-DedompHCDT.html#eq:Raobeta">(12.15)</a> :</p>
<ul>
<li>
<span class="math inline">\(H_{\Delta }\left(\mathbf{p}\right)\)</span> : diversité totale. Calculer <span class="math inline">\(\mathbf{p}\)</span> en sommant les communautés. Calculer ensuite l’entropie quadratique avec <code>divc</code> :</li>
</ul>
<p></p>
<div class="sourceCode" id="cb289"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="op">(</span><span class="va">tabF</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/apply.html">apply</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">phyf</span><span class="op">$</span><span class="va">leaves</span><span class="op">)</span>, <span class="op">]</span>, MARGIN <span class="op">=</span> <span class="fl">1</span>, <span class="va">sum</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##  Sr Ess  Me  S1  Bg  Ef  Vm  Dg 
## 284 228 139  91 173 169 141 221</code></pre>
<div class="sourceCode" id="cb291"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/divc.html">divc</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">tabF</span><span class="op">)</span>, <span class="va">phyf</span><span class="op">$</span><span class="va">Wdist</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      diversity
## tabF  5.870667</code></pre>
<p></p>
<ul>
<li>
<span class="math inline">\(H_{\Delta}\left({\mathbf{p}}_i\right)\)</span> : diversité de chaque communauté, fournie par <code>divc</code> :</li>
</ul>
<p></p>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/divc.html">divc</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">phyf</span><span class="op">$</span><span class="va">leaves</span><span class="op">)</span>, <span class="op">]</span>, <span class="va">phyf</span><span class="op">$</span><span class="va">Wdist</span><span class="op">)</span></span></code></pre></div>
<pre><code>##    diversity
## P1  5.816719
## P2  5.897210
## P3  5.744483
## P4  4.790586</code></pre>
<p></p>
<ul>
<li>La variabilité inter-communautés peut être calculée par <code>divc</code> en utilisant la distance fournie par <code>disc</code>, en définissant la matrice des poids (égale aux effectifs) :</li>
</ul>
<p></p>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/divc.html">divc</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">)</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/pkg/ade4/man/disc.html">disc</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">phyf</span><span class="op">$</span><span class="va">leaves</span><span class="op">)</span>,</span>
<span>    <span class="op">]</span>, <span class="va">phyf</span><span class="op">$</span><span class="va">Wdist</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>##                    diversity
## colSums(effectifs) 0.2362187</code></pre>
<p></p>
<p>La fonction <code>disc</code> calcule <span class="math inline">\(\sqrt{2D_{H_{\Delta}}\left({\mathbf{p}}_i,{\mathbf{p}}_j\right)}\)</span> :</p>
<p></p>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/pkg/ade4/man/disc.html">disc</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">phyf</span><span class="op">$</span><span class="va">leaves</span><span class="op">)</span>, <span class="op">]</span>, <span class="va">phyf</span><span class="op">$</span><span class="va">Wdist</span><span class="op">)</span></span></code></pre></div>
<pre><code>##           P1        P2        P3
## P2 0.4698121                    
## P3 0.4888729 0.6487916          
## P4 1.0018983 0.8776582 1.3157902</code></pre>
<p></p>
<p>Une interprétation géométrique de la décomposition est la suivante <span class="citation">(<a href="references.html#ref-Pavoine2004">Pavoine, Dufour, et Chessel 2004</a>)</span>.
Les espèces peuvent être placées dans un espace multidimensionnel construit par une Analyse en Coordonnées Principales <span class="citation">(<a href="references.html#ref-Gower1966">Gower 1966</a>)</span> de la matrice de dissimilarité <span class="math inline">\(\mathbf{D}\)</span> telle que <span class="math inline">\(\mathbf{\Delta}={\mathbf{D}^{\circ2}}/{2}\)</span> (les distances dans l’espace multidimensionnel sont <span class="math inline">\(\sqrt{2\delta_{s's''}}\)</span><span style="white-space:nowrap"> ;</span> autrement dit : la dissimilarité entre deux espèces est la moitié du carré de la distance entre elles dans la représentation géométrique).
Chaque communauté se trouve au centre de gravité des espèces qu’elle contient, pondérées par leur fréquence.
La moitié du carré de la distance entre deux communautés dans ce même espace est le coefficient de dissimilarité entre communautés de Rao.
La distance entre communautés est donc interprétable directement comme une mesure de diversité <span class="math inline">\(\beta\)</span> <span class="citation">(<a href="references.html#ref-Ricotta2015">Ricotta et al. 2015</a>)</span>, dans la tradition de l’utilisation de la dissimilarité entre paires de communautés (chapitre <a href="chap-BetaPaires.html#chap-BetaPaires">11</a>).</p>
<p>Cette partition suppose que les poids des communautés sont proportionnels à leur nombre d’individus <span class="citation">(<a href="references.html#ref-Rao1982">Rao 1982</a>; <a href="references.html#ref-Villeger2008">Villéger et Mouillot 2008</a>)</span>.
<span class="citation">O. J. Hardy et Senterre (<a href="references.html#ref-Hardy2007">2007</a>)</span> décomposent (par différence entre <span class="math inline">\(\gamma\)</span> et <span class="math inline">\(\alpha\)</span>) l’indice de Rao de communautés de poids égaux.
<span class="citation">O. J. Hardy et Jost (<a href="references.html#ref-Hardy2008">2008</a>)</span> montrent que les deux pondérations sont valides mais l’absence de cadre général assurant que la diversité <span class="math inline">\(\gamma\)</span> de Rao est supérieure à la diversité <span class="math inline">\(\alpha\)</span> <span class="citation">(<a href="references.html#ref-DeBello2010">de Bello et al. 2010</a>)</span> motive <span class="citation">Guiasu et Guiasu (<a href="references.html#ref-Guiasu2011">2011</a>)</span> à proposer une alternative à l’indice de Rao, l’indice de Gini-Simpson quadratique pondéré <a href="mesures-particuli%C3%A8res.html#eq:Guiasu">(7.24)</a>, dont la concavité est démontrée (ce qui implique que <span class="math inline">\(\gamma\ge \alpha\)</span>).
La pondération peut en fait être quelconque tant que la matrice dont les éléments sont la racine carré des éléments de la matrice de dissimilarité est euclidienne <span class="citation">(<a href="references.html#ref-Champely2002">Champely et Chessel 2002</a>)</span>.
Ce résultat a été obtenu pour les arbres ultramétriques dans le cadre plus général de la décomposition de l’entropie phylogénétique (voir chapitre <a href="chap-DedompHCDT.html#chap-DedompHCDT">12</a>.</p>
<p>La partition peut être faite avec la fonction <code>DivPart</code> :</p>
<p></p>
<div class="sourceCode" id="cb299"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Création d'une méta-communauté, poids égaux aux effectifs</span></span>
<span><span class="va">MC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/MetaCommunity.html">MetaCommunity</a></span><span class="op">(</span><span class="va">effectifs</span>, <span class="fu"><a href="https://rdrr.io/r/base/colSums.html">colSums</a></span><span class="op">(</span><span class="va">effectifs</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/DivPart.html">DivPart</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">2</span>, <span class="va">MC</span>, Tree <span class="op">=</span> <span class="va">phyf</span>, Normalize <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<pre><code>## HCDT diversity partitioning of order 2 of metaCommunity MC
## 
## Phylogenetic or functional diversity was calculated
## according to the tree 
## phyf 
## 
## Diversity is not normalized 
## 
## Alpha diversity of communities: 
##       P1       P2       P3       P4 
## 24.19203 24.70000 23.75363 19.16686 
## Total alpha diversity of the communities: 
##        9 
## 23.11553 
## Beta diversity of the communities: 
##        9 
## 1.061198 
## Gamma diversity of the metacommunity: 
##        9 
## 24.53015</code></pre>
<p></p>
<p>La décomposition de la diversité (et non seulement de l’entropie) de Rao a été établie par <span class="citation">Ricotta et Szeidl (<a href="references.html#ref-Ricotta2009">2009</a>)</span>.</p>
</div>
<div id="synthèse-4" class="section level2" number="12.6">
<h2>
<span class="header-section-number">12.6</span> Synthèse<a class="anchor" aria-label="anchor" href="#synth%C3%A8se-4"><i class="fas fa-link"></i></a>
</h2>
<p>La diversité mesurée par l’entropie généralisée peut être décomposée dans tous les cas de figure, y compris lorsque les poids des communautés ne sont pas égaux.
Les formules d’entropie et de diversité sont résumées dans le tableau <a href="chap-DedompHCDT.html#tab:Decomposition">12.3</a>.
L’entropie <span class="math inline">\(\beta\)</span> est une mesure de divergence entre la distribution de chaque communauté et celle de la méta-communauté, comme l’avaient suggéré <span class="citation">Ricotta et Burrascano (<a href="references.html#ref-Ricotta2009a">2009</a>)</span>.</p>
<p>L’entropie de Shannon est un cas particulier dans lequel toutes les controverses disparaissent : l’entropie <span class="math inline">\(\beta\)</span> est indépendante de l’entropie <span class="math inline">\(\alpha\)</span>, et la pondération de Jost se confond avec celle de Routledge.</p>
<p>L’entropie de Simpson peut être décomposée de deux façons : comme une variance quand les poids des communautés sont donnés par leurs effectifs, ou selon le cas général.
Les deux décompositions produisent les mêmes valeurs d’entropie <span class="math inline">\(\beta\)</span>, mais la contribution de chaque communauté n’est pas la même.</p>
<p>L’entropie peut être décomposée hiérarchiquement sur plusieurs niveaux <span class="citation">(<a href="references.html#ref-Crist2003">Crist et al. 2003</a>; <a href="references.html#ref-Marcon2012a">Marcon et al. 2012</a>)</span>.</p>
<p>Les probabilités d’occurrence des espèces ne sont pas connues mais estimées à partir des données.
Les diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span> sont sous-estimées et la diversité <span class="math inline">\(\beta\)</span> surestimée <span class="citation">(<a href="references.html#ref-Marcon2012a">Marcon et al. 2012</a>; <a href="references.html#ref-Beck2013">J. Beck, Holloway, et Schwanghart 2013</a>)</span>, d’autant plus que l’ordre de diversité est faible (le biais est négligeable au-delà de l’indice de Simpson).
Des méthodes de correction existent, mais pas pour l’entropie <span class="math inline">\(\beta\)</span> à l’exception de Shannon.
La méthode générale consiste donc à corriger les entropies <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span>, calculer l’entropie <span class="math inline">\(\beta\)</span> par différence et transformer les résultats en nombres équivalents <span class="citation">(<a href="references.html#ref-Marcon2014a">Marcon et al. 2014</a>; <a href="references.html#ref-Marcon2014e">Marcon, Zhang, et Hérault 2014</a>)</span>.</p>
</div>
<div id="normalisation" class="section level2" number="12.7">
<h2>
<span class="header-section-number">12.7</span> Normalisation<a class="anchor" aria-label="anchor" href="#normalisation"><i class="fas fa-link"></i></a>
</h2>
<p>La mesure de diversité <span class="math inline">\(^{q}\!D_{\beta}\)</span> est le nombre équivalent de communautés totalement distinctes qui fourniraient ce niveau de diversité.</p>
<div id="nécessité-de-normaliser-la-diversité-beta" class="section level3" number="12.7.1">
<h3>
<span class="header-section-number">12.7.1</span> Nécessité de normaliser la diversité <span class="math inline">\(\beta\)</span><a class="anchor" aria-label="anchor" href="#n%C3%A9cessit%C3%A9-de-normaliser-la-diversit%C3%A9-beta"><i class="fas fa-link"></i></a>
</h3>
<p>Selon une première approche, cette mesure n’a de sens que comparée à nombre de communautés.
La diversité entre un hectare de forêt tropicale et un hectare de forêt tempérée (de même poids, sans espèce commune) est égale à 2 quel que soit <span class="math inline">\(q\)</span>.
La diversité entre un nombre suffisant d’échantillons de forêt tropicale relativement homogène (avec de nombreuses espèces communes) peut facilement dépasser 2 : c’est le cas des 50 carrés de BCI pour <span class="math inline">\(q=0\)</span>.
Pour ne pas conclure de façon erronée que les carrés de BCI sont plus différents entre eux que BCI et la forêt de Fontainebleau, <span class="citation">Jost (<a href="references.html#ref-Jost2007">2007</a>)</span> suggère de diviser la diversité <span class="math inline">\(\beta\)</span> par le nombre de communautés pour la normaliser.
Ce raisonnement a un sens quand la diversité maximale envisageable est effectivement égale au nombre de communautés, par exemple si les communautés sont choisies dans des habitats différents : la diversité <span class="math inline">\(\beta\)</span> mesure cette différence.</p>
<p>Un autre cas est envisageable : les communautés peuvent être des échantillons d’une méta-communauté clairement définie.
La diversité <span class="math inline">\(\beta\)</span> mesure alors la variabilité de l’échantillonnage à l’intérieur de la méta-communauté à une échelle donnée.
Pour une taille d’échantillon fixée (par exemple un hectare de forêt), la diversité <span class="math inline">\(\beta\)</span> ne dépend pas du nombre de communautés : l’entropie <span class="math inline">\(\beta\)</span> est l’espérance (estimée par la moyenne, équation <a href="chap-DedompHCDT.html#eq:ContributionBeta">(12.5)</a> de la divergence de Jensen-Shannon entre la distribution des espèces d’une communauté et celle de la méta-communauté, fixe.
Cette variabilité dépend de l’échelle de l’échantillonnage dans le sens où elle diminue si les échantillons sont de taille plus grande : l’entropie <span class="math inline">\(\alpha\)</span> de deux hectares de forêts est la diversité <span class="math inline">\(\alpha\)</span> moyenne de chacun des deux hectares plus l’entropie <span class="math inline">\(\beta\)</span> entre eux.
L’entropie <span class="math inline">\(\beta\)</span> entre les échantillons de deux hectares est donc diminuée de cette entropie <span class="math inline">\(\beta\)</span> “intra” qui est absorbée par la nouvelle entropie <span class="math inline">\(\alpha\)</span> quand la taille des échantillons augmente.</p>

<p></p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:BetaSampleFig"></span>
<img src="MesuresBD_files/figure-html/BetaSampleFig-1.png" alt="Estimation de la diversité \(\beta\) entre carrés de BCI. La diversité est calculée à partir du nombre de carrés en abscisse, de 2 à 30, tirés aléatoirement. La valeur en ordonnée est la diversité d’ordre 2 moyenne sur 100 tirages, les barres représentent l’écart-type. Aux erreurs d’estimation près et dès 5 carrés (nécessaires pour représenter l’ensemble du dispositif), la valeur de la diversité \(\beta\) ne dépend pas du nombre de carrés. La ligne horizontale représente la diversité \(\beta\) entre tous les carrés." width="80%"><p class="caption">
Figure 12.1: Estimation de la diversité <span class="math inline">\(\beta\)</span> entre carrés de BCI. La diversité est calculée à partir du nombre de carrés en abscisse, de 2 à 30, tirés aléatoirement. La valeur en ordonnée est la diversité d’ordre 2 moyenne sur 100 tirages, les barres représentent l’écart-type. Aux erreurs d’estimation près et dès 5 carrés (nécessaires pour représenter l’ensemble du dispositif), la valeur de la diversité <span class="math inline">\(\beta\)</span> ne dépend pas du nombre de carrés. La ligne horizontale représente la diversité <span class="math inline">\(\beta\)</span> entre tous les carrés.
</p>
</div>
<p></p>
<p>La figure <a href="chap-DedompHCDT.html#fig:BetaSampleFig">12.1</a> présente les valeurs estimées de diversité neutre <span class="math inline">\(\beta\)</span> entre carrés de BCI tirés aléatoirement, en fonction du nombre de carrés.</p>
<p>Code pour réaliser la figure :</p>
<p></p>
<div class="sourceCode" id="cb301"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Metacommunauté de BCI</span></span>
<span><span class="va">MC</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/MetaCommunity.html">MetaCommunity</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">BCI</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Création d'une méta-communauté à partir de n carrés de BCI </span></span>
<span><span class="va">SamplePlots</span> <span class="op">&lt;-</span> <span class="kw">function</span> <span class="op">(</span><span class="va">n</span>, <span class="va">q</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">Plots</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">50</span>, <span class="va">n</span><span class="op">)</span></span>
<span>  <span class="va">Nsi</span> <span class="op">&lt;-</span> <span class="va">MC</span><span class="op">$</span><span class="va">Nsi</span><span class="op">[</span>, <span class="va">Plots</span><span class="op">]</span>; <span class="va">MCsample</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/MetaCommunity.html">MetaCommunity</a></span><span class="op">(</span><span class="va">Nsi</span><span class="op">)</span></span>
<span>  <span class="va">dp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/DivPart.html">DivPart</a></span><span class="op">(</span><span class="va">q</span>, <span class="va">MCsample</span>, Biased <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>  <span class="co"># Retourne la diversité beta</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">dp</span><span class="op">$</span><span class="va">TotalBetaDiversity</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co"># Calcul de la diversité moyenne à partir des simulations</span></span>
<span><span class="va">BetaPlots</span> <span class="op">&lt;-</span> <span class="kw">function</span> <span class="op">(</span><span class="va">q</span>, <span class="va">nPlots</span>, <span class="va">nSimulations</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="va">buiw</span> <span class="op">&lt;-</span> <span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/vector.html">vector</a></span><span class="op">(</span><span class="st">"numeric"</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">nPlots</span><span class="op">)</span><span class="op">)</span>; <span class="va">i</span> <span class="op">&lt;-</span> <span class="fl">1</span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">Size</span> <span class="kw">in</span> <span class="va">nPlots</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="va">Sims</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/lapply.html">replicate</a></span><span class="op">(</span><span class="va">nSimulations</span>, <span class="fu">SamplePlots</span><span class="op">(</span><span class="va">Size</span>, <span class="va">q</span><span class="op">)</span><span class="op">)</span>  </span>
<span>    <span class="va">b</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">Sims</span><span class="op">)</span></span>
<span>    <span class="va">buiw</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">Sims</span><span class="op">)</span></span>
<span>    <span class="va">i</span> <span class="op">&lt;-</span> <span class="va">i</span><span class="op">+</span><span class="fl">1</span></span>
<span>  <span class="op">}</span></span>
<span>  <span class="co"># Retour d'un dataframe</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x<span class="op">=</span><span class="va">nPlots</span>, y<span class="op">=</span><span class="va">b</span>, ymin<span class="op">=</span><span class="va">b</span><span class="op">-</span><span class="va">buiw</span>, ymax<span class="op">=</span><span class="va">b</span><span class="op">+</span><span class="va">buiw</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span></span>
<span><span class="co"># Echantillonnage de la diversité beta</span></span>
<span><span class="va">BetaD</span> <span class="op">&lt;-</span> <span class="fu">BetaPlots</span><span class="op">(</span>q <span class="op">=</span> <span class="fl">2</span>, nPlots<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fl">5</span>, <span class="fl">10</span>, <span class="fl">15</span>, <span class="fl">20</span>, <span class="fl">25</span>, <span class="fl">30</span><span class="op">)</span>, </span>
<span>          nSimulations <span class="op">=</span> <span class="fl">100</span><span class="op">)</span></span>
<span><span class="co"># Diversité beta totale</span></span>
<span><span class="va">dpBCI</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ericmarcon.github.io/entropart/reference/DivPart.html">DivPart</a></span><span class="op">(</span>q <span class="op">=</span> <span class="fl">2</span>, <span class="va">MC</span>, Biased <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span><span class="co"># Figure</span></span>
<span><span class="fu">ggplot</span><span class="op">(</span><span class="va">BetaD</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, y<span class="op">=</span><span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="fu">geom_errorbar</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">x</span>, ymin<span class="op">=</span><span class="va">ymin</span>, ymax<span class="op">=</span><span class="va">ymax</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="va">dpBCI</span><span class="op">$</span><span class="va">TotalBetaDiversity</span>, lty<span class="op">=</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu">labs</span><span class="op">(</span>x<span class="op">=</span><span class="st">"Nombre de carrés"</span>, </span>
<span>       y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/expression.html">expression</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="st">"Diversité "</span>, <span class="va">beta</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<p></p>
<p>L’estimation de la diversité présente les difficultés classiques dues au biais d’estimation : la diversité <span class="math inline">\(\gamma\)</span> est sous-estimée si l’échantillonnage est trop faible, la diversité <span class="math inline">\(\beta\)</span> augmente avec le nombre de communautés comme la diversité <span class="math inline">\(\gamma\)</span> augmente avec la taille de <span style="white-space:nowrap">l’échantillon ;</span> il s’agit d’un problème d’estimation, pas de normalisation.</p>
<p>La diversité <span class="math inline">\(\beta\)</span> ne doit donc pas être normalisée systématiquement, mais seulement dans le premier cas.</p>
</div>
<div id="sec-Chevauchement" class="section level3" number="12.7.2">
<h3>
<span class="header-section-number">12.7.2</span> L’indice de chevauchement <span class="math inline">\(C_{qN}\)</span><a class="anchor" aria-label="anchor" href="#sec-Chevauchement"><i class="fas fa-link"></i></a>
</h3>
<p>Plutôt qu’une simple normalisation, <span class="citation">Chao et al. (<a href="references.html#ref-Chao2008">2008</a>)</span> définissent un indice de chevauchement, c’est-à-dire la proportion d’espèces partagées en moyenne par une communauté.
Si <span class="math inline">\(N\)</span> communautés (le nombre de communautés est noté <span class="math inline">\(N\)</span> ici et non <span class="math inline">\(I\)</span> pour conserver le nom de l’indice établi dans la littérature) de mêmes diversités <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\gamma\)</span> que les données, contenaient chacune <span class="math inline">\(S\)</span> espèces équifréquentes, dont <span class="math inline">\(A\)</span> seraient communes à toutes les communautés et les autres représentées dans une seule, <span class="math inline">\(A/S\)</span> serait cet indice de chevauchement.</p>
<p>Pour <span class="math inline">\(q\ne 1\)</span>,</p>
<p><span class="math display" id="eq:Chao2008q">\[\begin{equation}
  \tag{12.16}
  C_{qN} = {\left[{\left(\frac{1}{^{q}\!D_{\beta}}\right)}^{q-1}-{\left(\frac{1}{N}\right)}^{q-1}\right]}/{\left[1-{\left(\frac{1}{N}\right)}^{q-1}\right]}
\end{equation}\]</span></p>
<p>et</p>
<p><span class="math display" id="eq:C1N">\[\begin{equation}
  \tag{12.17}
  C_{1N}
  =\frac{1}{\ln{N}}\sum^S_{s=1}{\sum^N_{i=1}{\frac{p_{s|i}}{N}\ln\left(1+\frac{\sum_{j\ne i}{p_{sj}}}{p_{s|i}}\right)}}
  =1-\frac{H_{\beta}}{\ln{N}}.
\end{equation}\]</span></p>
<p><span class="math inline">\(C_{qN}\)</span> a été défini à l’origine pour <span class="math inline">\(q\ge 2\)</span>.
<span class="citation">Chao, Chiu, et Hsieh (<a href="references.html#ref-Chao2012a">2012</a>)</span> l’étendent sans précaution à <span class="math inline">\(q\)</span> quelconque.
Sa valeur peut être négative pour <span class="math inline">\(q&lt;1\)</span>, on se limitera donc à <span class="math inline">\(q \ge 1\)</span>.</p>
</div>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="chap-BetaPaires.html"><span class="header-section-number">11</span> Diversité de différentiation</a></div>
<div class="next"><a href="d%C3%A9composition-de-la-diversit%C3%A9-phylog%C3%A9n%C3%A9tique-et-fonctionnelle.html"><span class="header-section-number">13</span> Décomposition de la diversité phylogénétique et fonctionnelle</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#chap-DedompHCDT"><span class="header-section-number">12</span> Décomposition de l’entropie HCDT</a></li>
<li>
<a class="nav-link" href="#d%C3%A9composition-de-lindice-de-shannon"><span class="header-section-number">12.1</span> Décomposition de l’indice de Shannon</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#d%C3%A9finition-3"><span class="header-section-number">12.1.1</span> Définition</a></li>
<li><a class="nav-link" href="#sec-BiaisShannonBeta"><span class="header-section-number">12.1.2</span> Biais d’estimation</a></li>
</ul>
</li>
<li><a class="nav-link" href="#d%C3%A9composition-de-lentropie-g%C3%A9n%C3%A9ralis%C3%A9e"><span class="header-section-number">12.2</span> Décomposition de l’entropie généralisée</a></li>
<li><a class="nav-link" href="#d%C3%A9composition-du-nombre-desp%C3%A8ces"><span class="header-section-number">12.3</span> Décomposition du nombre d’espèces</a></li>
<li><a class="nav-link" href="#d%C3%A9composition-de-lindice-de-gini-simpson"><span class="header-section-number">12.4</span> Décomposition de l’indice de Gini-Simpson</a></li>
<li><a class="nav-link" href="#sec-RaoDisc"><span class="header-section-number">12.5</span> Décomposition de l’indice de Rao</a></li>
<li><a class="nav-link" href="#synth%C3%A8se-4"><span class="header-section-number">12.6</span> Synthèse</a></li>
<li>
<a class="nav-link" href="#normalisation"><span class="header-section-number">12.7</span> Normalisation</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#n%C3%A9cessit%C3%A9-de-normaliser-la-diversit%C3%A9-beta"><span class="header-section-number">12.7.1</span> Nécessité de normaliser la diversité \(\beta\)</a></li>
<li><a class="nav-link" href="#sec-Chevauchement"><span class="header-section-number">12.7.2</span> L’indice de chevauchement \(C_{qN}\)</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/EricMarcon/MesuresBioDiv2/blob/master/04-Beta.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/EricMarcon/MesuresBioDiv2/edit/master/04-Beta.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Mesures de la Biodiversité</strong>" was written by Eric Marcon. It was last built on 05/12/2024.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
